### ISSUE TITLE
Global paid events

### ISSUE THREAD

**Issue by EvilCh33z** [Erigitic/TotalEconomy#112]

**Comment by EvilCh33z** [comment]
Paid events that apply to all jobs by default with a per-job option to exclude from.
I think something like this in config:

Global {
    Event {
        Block/item {
            Reward=reward
        }
     }
}
Examplejob {
    Events {}
    Options=options
    GlobalPay=true/false
}

**Comment by Erigitic** [comment]
Let me know if I understand this correctly. You are suggesting that certain blocks, for example, will give out a reward, such as money, regardless of the user's job?

**Comment by EvilCh33z** [comment]
Yes And then an option to exclude from global paid events per job like "unemployed people can't earn pay for base actions." And "anyone with any job except X gets base payout for these blocks..."

**Comment by MarkL4YG** [comment]
I would suggest to add "payment"-sets that the administrator can apply to multiple jobs and the job "unemployed" as a default job.

This way jobs could in- and exclude certain sets to change how what action is being paid.
You could also add a payment-multiplier (in percent to the job-node and maybe even set-dependent) in order to give jobs of higher tier a higher payment for the same actions.

this also could make it easier to set up payments for jobs which have overlapping payments e.g. for modded blocks which tend to have fairly long IDs so these would only have to be entered once.
