### ISSUE TITLE
Access to dev-builds

### ISSUE THREAD

**Issue by yololetsplay** [Erigitic/TotalEconomy#139]
Hey  @Erigitic and @MarkL4YG ;]

Well, is there any way to get access to in-development builds and beta-test this on my official community server?
I would leave you feedback every day if there is something I find out ;]

Greetz,
Hannes

**Comment by MarkL4YG** [comment]
Well, if we don't compile and upload one, you could clone the repo yourself and run the compilation.
In theory:
1. Install "git bash"
2. open a command window and go to a directory of your choice (Desktop e.g.)
3. ``git clone --recursive https://github.com/Erigitic/TotalEconomy``
3. ``git clone --recursive https://github.com/MarkL4YG/TotalEconomy`` - If you want my fork
3. You may add ``--branch <branch>`` if you want to clone a specific branch
4. ``gradlew setupDevWorkspace``
5. ``gradlew build``

The .jar is located under ``build/libs``.


---
I wouldn't recommend setting this live on an official server though!
Dev build are always considered unstable until proven otherwise and this would be a dev-SNAPSHOT that doesn't even have to compile without errors...

Additionally @Erigitic doesn't instantly push his code commits which delays their availability in the public repo. (This is the developers choice, some wait, some don't)

And on top of that: Since @Erigitic doesn't seem to wait to create a release once the coding is done, there's not really a point of doing dev-builds at all. New features don't seem to sit around until a normal release is done.

**Comment by Erigitic** [comment]
@yololetsplay I tend to complete a feature to the point where it is fully functional, then release it. So there is no space in between for development releases. All a development release would be, at least for this project, would be a half finished feature, and I don't really see a point in that. If you really want to run a development build then do what @MarkL4YG stated above. It is quite the process though if you have never done it before. I will admit that I do need to push my code more often and this is something I will begin doing.
