### ISSUE TITLE
Multi-Currency support

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#156]
### Config Changes
- [x] Config option to set whether or not currency can be transferred to other players or not.

### Wiki
- [ ] Update wiki for multi currency support

### Commands to update
- [x] AdminPay
- [x] Balance
- [x] Pay
- [x] SetBalance
- [x] ViewBalance

**Comment by MarkL4YG** [comment]
You could define the ``amount`` parameter of transaction commands to support any number for using the default currency and a currency-specified form like ``300Coins``. Seperating them is easy with regex since the number always matches ``[0-9]+`` while the currency name would always match ``[a-zA-Z]+``.

Exchange rates and multiple currencies could be defined like this:
```hocon
currency {
  dollar {
    singular=Dollar
    plural=Dollars
    symbol="$"
  }
  beli {
    singular=Beli
    plural=Beli
    symbol="§"
   exchange {
     dollar=2.5
    }
  }
  coin {
    singular=Coin
    plural=Coins
    symbol="C"
  }
}
```
Note that ``coin`` doesn't have an exchange note thus exchange into other currencies could be disabled.

I would also recommend a command that allows users to define their default currency so one doesn't end up with an account holding a variety of different currencies. (Currencies exchangeable to the default could then just be exchanged automatically upon receive)
The balance command could display the default currencies amount, calculate what that would be in other currencies and also display those. Non-exchangeable currencies would be displayed on their own of course.

I would not code a path finding code to check if one currency is exchangeable to another via a third - I think this might be a bit over the top.

**Comment by Zerthick** [comment]
Summarizing my previous issue, in order for plugin developers to properly interface with multiple currencies [EconomyService#getCurrencies()](https://jd.spongepowered.org/6.0.0/org/spongepowered/api/service/economy/EconomyService.html#getCurrencies--) must be properly implemented to return a list of all currencies (currently an empty HashSet is returned). In addition a [Currency](https://jd.spongepowered.org/6.0.0/org/spongepowered/api/service/economy/Currency.html) is a [CatalogType](https://jd.spongepowered.org/6.0.0/org/spongepowered/api/CatalogType.html) and as such, should be registered in the [GameRegistry](https://jd.spongepowered.org/6.0.0/org/spongepowered/api/GameRegistry.html) during initialization. This will allow developers to fetch them from the registry as well as do things like easily take a currency as an argument to a command.
