### ISSUE TITLE
Set job to a player

### ISSUE THREAD

**Issue by MindThoth** [Erigitic/TotalEconomy#166]
I'm trying to find a way to set a job to a player for example : /job set playername jobname
But that command doesn't exist is there a way to do this?

**Comment by MarkL4YG** [comment]
I guess currently you can just change it in the config.

**Comment by MarkL4YG** [comment]
@Erigitic we could add a ``player`` argument to the command for this. Or even make it a ``User`` to allow changing jobs for other users who are offline. The last would require a few more changes outside the command though.

**Comment by MindThoth** [comment]
Well Im trying to set so people can't select all the jobs. For example guest don't have the permission to have member jobs. I tried adding job permission to the member group but it seems as if you give the /job set command they are able to access all the jobs. If I remove the /job set permission they aren't able to choose a job.

**Comment by MarkL4YG** [comment]
@MindThoth what version of Sponge and TE are you running?

**Comment by MindThoth** [comment]
Sponge 1.10.2 - 2254 5.2.0 BETA 2236 with TotalEconomy v1.5.3

**Comment by MarkL4YG** [comment]
As you can see [here](https://github.com/Erigitic/TotalEconomy/blob/1c44437f3b2b38f6c8be15dd6adea010a019fc96/src/main/java/com/erigitic/jobs/TEJobs.java#L248) there're two ways for permitting user to join a job.
1. Use job permissons ``totaleconomy.job.<jobName>``
or
2. Don't use job permissions so all jobs can be joined by anyone.

However this changes in the upcoming release since the new job system allows you to set custom requirements for a job. In those you can define a permission and/or another job which has to be leveled to a certain level. This enables more precise restrictions for joining jobs.

**Comment by MindThoth** [comment]
This is how I have it setup in the Jobs.config

I tried adding the totaleconomy.job.member permission to the group member and unemployed are still able to set jobs to member

```
Unemployed {
    disablesalary=false
    salary=5
}

Member {
    disablesalary=false
    permission="totaleconomy.job.member"
    salary=20
}
```

**Comment by MarkL4YG** [comment]
Up to version 1.5.3 you need to enable job-permissions in the ``totaleconomy.conf`` to do that set ``permissions`` under ``features`` >> ``jobs`` to ``true``.

The ``permission`` node you created in the job definition has no effect because the plugin automatically uses ``totaleconomy.job.<name>`` for that. Also the job names should be completely lowercase since they're used as identifiers.

**Comment by MindThoth** [comment]
ahhh that would make sense! Thanks

**Comment by MarkL4YG** [comment]
@MindThoth you're welcome. Please tell me if you were able to resolve your issue :)

**Comment by MarkL4YG** [comment]
The PR adds the command ``job set <job> <player>`` which would allow you to set others jobs.
They still need to meet the requirements though.
