### ISSUE TITLE
Negative balance.

### ISSUE THREAD

**Issue by AzttecHD** [Erigitic/TotalEconomy#171]
Hello I was reading before that you said you had fixed negative balance, I am having trouble on my server with players buying claim blocks from grief prevention, but they can buy as many as they want, my test account is now -$450675 so something isn't right any ideas

**Comment by MarkL4YG** [comment]
In the ``#withdraw`` function of the ``TEAccount`` class is no actual limitation to deny having negative balance. The ``#transfer`` method however doesn't not allow this. Since Grief Prevention is not really getting paid the payments count as withdrawals.
@Erigitic may consider to implement ``ACCOUNT_NO_FUNDS`` for this too.
Maybe allow admins to set lower bounds.

**Comment by Erigitic** [comment]
That's not good. A check will be added.

**Comment by Erigitic** [comment]
Actually I was just looking over the code, and yes a check for a negative balance is not in the withdraw function, but it is being done in the setBalance function that it calls.

Are you using the 1.6.0-DEV version @AzttecHD?

**Comment by AzttecHD** [comment]
Yes I am using 1.6.0-dev

**Comment by MarkL4YG** [comment]
@Erigitic Seems like my fork needs an update then... And also: Does the develop branch happen to be ahead of the preview here?

**Comment by Erigitic** [comment]
A bit yeah. I thought the change fixing this issue was released with that latest development release. I'll check on the commit history to see for sure.

**Comment by MarkL4YG** [comment]
@Erigitic while you're on that: Consider adding a build number to the pre-releases :)
