### ISSUE TITLE
Cataloge Currencies and implement EconomyService#getCurrencies() 

### ISSUE THREAD

**Issue by Zerthick** [Erigitic/TotalEconomy#183]
Hello!  Currently the default currency created by TotalEconomy is not registered with the GameRegistry, nor is it contained in the set returned by `EconomyService#getCurrencies()` (you currently just return an empty HashSet).  While this currently isn't much of an issue if you only have a default currency, this becomes absolutely essential for developers interfacing with the EconomyService such as myself if you ever intend to support multiple currencies.

**Comment by Erigitic** [comment]
Please post this over on this issue: https://github.com/Erigitic/TotalEconomy/issues/156. This way we can contain the multi-currency issue on a single page instead of two. Also, I was not aware that currencies needed to be registered with the GameRegistery. If you could explain this more, on the issue linked above, we'll gladly get it squared away. Thanks.
