### ISSUE TITLE
Add a template.sql file

### ISSUE THREAD

**Issue by Erigitic** [Erigitic/TotalEconomy#184]
@MarkL4YG Would this be necessary considering this is all done within the plugin itself? It also seems that executing an SQL script from java is quite the chore.

**Comment by MarkL4YG** [comment]
I don't know how to import SQL dumps using Java. If that's considerably painful I would scratch that. Otherwise using SQL templates (dumps without data in fact) may turn out to be helpful to developers.  
It also means you don't have to run Sponge just to set up the database.  

This are only weak reasons though so if importing SQL dumps really isn't that easy I would lay this aside until it becomes necessary for some reason.
