### ISSUE TITLE
"Legacy" support

### ISSUE THREAD

**Issue by MarkL4YG** [Erigitic/TotalEconomy#191]
Hi @Erigitic ,
As I noticed by your latest git tag TE will no longer offer stable support for SpongeAPI 5.  
Since many modded servers (which currently mostly are stuck at <= 1.7.10) are currently working towards 1.10.2 I'd like to ask you to allow legacy builds from a separate branch so those can build TE for their Sponge version as necessary this'll also allow you to work on the latest builds while others (like me) can PR backports.

**Comment by Erigitic** [comment]
Quite the opposite actually! I was thinking we could start offering stable support for older versions, as well as continuing support for the latest versions. Because like you said, many servers are still running on older versions of Minecraft. I will create a separate branch for legacy versions so we can begin offering legacy builds of Total Economy. Feel free to submit PRs to it right away. Thanks as always.

**Comment by MarkL4YG** [comment]
I'm glad to hear that! ^^
