### ISSUE TITLE
latest api changes in sponge broke this plugin

### ISSUE THREAD

**Issue by hunter688** [Erigitic/TotalEconomy#204]
Sponge api changes around Cause broke many plugins include this.

https://github.com/SpongePowered/SpongeForge/commit/f43cb1c2b073be581a9f1ca1b4174d91d097ce90

**Comment by MarkL4YG** [comment]
We are aware of that. TotalEconomy currently aims at API 5 & 6 support and will need an API-7 branch due to those changes (which by the way originated from Mojang).  

While this is necessary I'd wait with proper implementation until the changes hit stable as they're currently in bleeding stage which may significantly change with each commit.  

If you happen to build TE for API 7 on your own for earlier use than supported go ahead and file a PR so others can benefit too. :)

**Comment by Erigitic** [comment]
I'm going to go ahead and close this as it's an issue related to a currently unsupported API version. When Total Economy is updated to API 7, and if the issue still persists, please feel free to open another issue. Thanks.
