### ISSUE TITLE
Friendly request ! <3

### ISSUE THREAD

**Issue by COLDYY1** [Erigitic/TotalEconomy#207]
I have a request. You might be able to add so you can disable individual jobs and not everyone. You may just want to have some active jobs while having the other jobs disabled.

Kind Regards,
Daniel (COLDYY1)

**Comment by MarkL4YG** [comment]
To "disable" jobs just remove their node from the jobs.conf. Or did I get your request wrong?

**Comment by MarkL4YG** [comment]
The plugin is not yet ready for SpongeAPI 7 since that's a bleeding edge release with major changes to the ``NamedCause`` subsystem forced by Mojang. @Erigitic and I will discuss multi-API support in the Gitter channel as soon as he's got time again. For the time being either use SpongeAPI 5 or 6 releases or wait for the development release.
