### ISSUE TITLE
Perms not working for jobs

### ISSUE THREAD

**Issue by Millificent** [Erigitic/TotalEconomy#334]
Sponge Version:  1.12.2-2768-7.1.6-RC3616
Forge Version:   2811
Total Economy Version:  1.8.1

### Description of issue
Unable to get the job option to work while using luckperms
Tried to add various commands with little success.
Adding - totaleconomy.command.job allows /job command to be used but it still says no permission when clicking on the roles.

### Console errors
No permission to click role.
/job unavailable unless totaleconomy.command.job is used.
### Related Configuration Files
Create a Gist (https://gist.github.com/) for each configuration file related to this issue

https://gist.github.com/Millificent/d4db5bf2062920b289fcf3589d92a7b4

https://gist.github.com/Millificent/b98f23823aa31673c2d6f744636bba45

**Comment by MarkL4YG** [comment]
Did you check https://github.com/Erigitic/TotalEconomy/wiki/Command-Permissions and set your permissions up accordingly?

**Comment by Millificent** [comment]
Hey Mark,

I’ve tried all the perms I’ve trief the total command and all various separate ones and no matter what a job cannot be picked.

I’d rather use the branches of perms than the wildcard.

I can attack a git of luckperms if it helps?

**Comment by MarkL4YG** [comment]
If you have the implicit wildcard enabled in Luckperms, granting a user `` totaleconomy.command.job`` will allow that user access to every job command (Related issue #205 ). Including ``totaleconomy.command.job.setother`` and ``.reload``.  
It is very likely you do not want that.  
  
When the implicit wildcard is disabled, a user must be granted ``totaleconomy.command.job`` to be allowed to use "/job" at all and ``totaleconomy.command.job.set`` in order to be able to set their own job.  
In addition, when the configured job requirements in the jobs configuration requires users to have a specified permission, that permission must also be granted in order for a user to be able to select that job.

**Comment by Millificent** [comment]
So the job does not have any specified permission and luck perms has each of the above commands in
https://imgur.com/a/GUm5z4K

**Comment by Millificent** [comment]
https://imgur.com/a/f7jALNy

**Comment by MarkL4YG** [comment]
Can you attach your jobs configuration using [a gist](https://gist.github.com).

**Comment by Millificent** [comment]
https://gist.github.com/Millificent/f75a45c2bea705ee5d2b17a145f9a070

**Comment by MarkL4YG** [comment]
Remove the permission requirements from your config and try again.  
Permission requirements are evaluated based on [a null check](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/commands/JobCommand.java#L141) and your configuration uses an empty string (which is not the same as ``null``)

**Comment by Millificent** [comment]
You are the hero...honestly 3 of us have played around with this for like a week solid

**Comment by MarkL4YG** [comment]
Glad to have helped 👍   
Feel free to close the issue if you don't have any related questions.

**Comment by MarkL4YG** [comment]
@Erigitic //dangling resolved issue :wink:

**Comment by Erigitic** [comment]
@MarkL4YG Thanks
