### ISSUE TITLE
Multi Currency?

### ISSUE THREAD

**Issue by Coolboyz347** [Erigitic/TotalEconomy#359]
Sponge Version:  1.12.2
Forge Version:  1.12.2
Total Economy Version:  1.8.1

### Description of issue
How do you create multi-currency?

**Comment by MarkL4YG** [comment]
If you take a look at your ``totaleconomy.conf``, you will see a section like this one:  
```
currency {
    dollar {
        currency-plural=dollars
        currency-singular=dollar
        default=true
        prefix-symbol=true
        startbalance="200"
        symbol="$"
        transferable=true
    }
}
```  
Copying the ``dollar`` section and pasting it after the closing ``}`` of the ``dollar`` section will give you the template for another currency. Rename the section key to the currency identifier you want to use and edit ``currency-plural``, ``currency-singular`` and ``symbol`` to match the lingo you want to use for the currency.  
__Note__: _If you use TotalEconomy with a database connected, you will have to manually add columns to your tables in order to support the new currency (the template can be found [here](https://github.com/Erigitic/TotalEconomy/blob/develop/src/main/java/com/erigitic/config/AccountManager.java#L149)). Deleting all tables and letting TotalEconomy initialize your tables will work but will cause you to loose all TE account data._

**Comment by Coolboyz347** [comment]
Got it thanxs!

**Comment by MarkL4YG** [comment]
You're welcome :wink:
