### ISSUE TITLE
[1.10.2 / Sponge / TotalEconomy 1.5.0] Some job Error

### ISSUE THREAD

**Issue by mister-man** [Erigitic/TotalEconomy#97]
Hallo together,

I found some problems with the jobs.
Prevent Farming doesnt work. The old console error is fiexed, but I get any  job farm like fish and wood.

Further dark oak dood isn't dedacted by the lumberjack job. No money and no xp gain.

Thanks

**Comment by Erigitic** [comment]
Prevent farming was replaced with what should be a much better alternative in v1.5.0. The new way it works is that if a player placed the block, then they will not gain exp/money for it. Regarding your other statement, I need to change some code to work with block alternatives such as dark oak.

**Comment by mister-man** [comment]
okay, thanks.

But I mean you should thing about Prevent farming. Prevent farming is more then an protection to make money with placed items. It's like an instant sell of the items. I use it on a mod server to prevent earn money from autofarming. But allow earn money from own work. Items that allowed autofarm can sell in an admin shop, but manuel items should use prefent farming.

Thanks :)

**Comment by Erigitic** [comment]
@mister-man I am a little confused as to what you are saying. Farming prevention is STILL present in Total Economy, it is just being handled differently. Are you wanting the option to enable/disable farming prevention to be able to be set for individual jobs?

**Comment by mister-man** [comment]
@Erigitic sorry for the late answer. the old farm prevention removes the blogs while farming. so you get money and no resources. like a player sells it. the new prevention only prevents earning money from player placed blogs, right?

and the old way is more than an prevention, it is a feature to disable earning money and matrials at the same time.

**Comment by Erigitic** [comment]
The old way no longer worked which is why it was replaced. I am not sure if I will go about adding the old way back, unless there is a big enough demand for it. I personally did not like the old way as it prevented the gaining of materials even when the block was not placed by the player. This new way allows the gaining of materials still but prevents any sort of "farming". Again, if there is high enough demand I will look into it, otherwise I think it would be best to keep it the way it is.

Regarding the other issue with blocks not being recognized, this will be fixed shortly. The goal is to release this alongside the next release.

**Comment by Erigitic** [comment]
Closing this as this issue, as well as a few others, have been consolidated into #105.
